name: Merge & Deploy to GitHub Pages

on:
  push:
    branches: [main]  # Trigger on push to the main branch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v3

      - name: 2. Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 3. Install dependencies
        run: |
          pip install -r requirements.txt

      - name: 4. Merge all member tags
        run: |
          python merge_tags.py

      - name: 5. Commit updated tags.json
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data/tags.json
          git commit -m "Auto-merged tags.json" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 6. Upload web files
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

      - name: 7. Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
